# Generated by Django 4.0.6 on 2022-07-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_client_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='sale',
        ),
    ]
