# Generated by Django 4.0.6 on 2022-07-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_client_sale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Order',
        ),
    ]
